behaviors:
  Thief:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 3000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true